version: '3'
services:
  strapi:
    container_name: cakrazemlak_strapi
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_NAME: cakraz
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
    volumes:
      - ./:/srv/app
    ports:
      - '1337:1337'
    depends_on:
      - postgres

  postgres:
    container_name: cakrazemlak_postgres
    image: postgres
    environment:
      POSTGRES_DB: cakraz
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi